services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obscur_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development